sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LHEsXHV9Ad6UxTBGQMR+aYIF2eVsjGqT8F7kmPLvNmSyu/ljiRYQ9226/ATs0PG3t9Bw3Tt4jANkSfNw/RmC74yJlFClUkWOMpgk9h3RogoVQgV7xaRJUqD/NS4xKgdi3yEADEf4Vxw0Nfzw99y+qieem2ekNNJ0VyyeeO+n9d1brAJqJbQ064vzMaujcWgk5JgfByQJHBP5aD3SVfg1ZMzN9UGIr+5KKwYPTUbAh17LrdHQ/Ki9BWHARM8ambDb1lALVbxmeUvJVuykruMKpQ5YCsab8nX2iBoQl3CFJB/S8m6tAtm4E2cZibI78cShxYZpRABcsZw+kt4do9LJogdH4Fa+Ayd+XMIC3GynOOPD5ZvGn2KPjgL97tDG3NN2x6xS1yMN8s34geqcbwHwa0T4wi/DQsbkpKSM1gteaOr9jSajTCHb0Mcdrn+c2Xa9sOn4lhnsoSC/ULdFSuqS5GNb1TOncwVc9fH9kBOp9yrSErtQK/jK1QGhIIJCs+a2D6h+xYaF6NS6F5bnMyYT7vm+scy5HHemd/fC234nLH/muvKu3XwRh1FgKfGkLtfOQ1nPAOKzRKexHAR+kPo2TFb/XRaBKYTNBZEdXxe9g2OG83C1HH2zFSVTgeE5UUTkQX7bLPhkyiDQp3RVkOxxBKPuh+83EMUl6vXxr8d1OHQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Franz-Haydn-s-104th-Symphony--1794-5-MIDI-file_276
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy